---
title: "Analysing Tennis's Big 3"
author: "Callan Pringle"
date: "2023-01-11"
output: pdf_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r, echo = FALSE}
library(tidyverse)
library(tibble)
library(ggplot2)
library(readxl)
```


```{r, echo = FALSE}
Big_3 <- read_excel('C:\\Users\\calla\\Desktop\\Github\\Big_3.xlsx')
```



```{r, echo = FALSE}
ggplot(Big_3, aes(year, gs_won)) +
  geom_line(aes(color = player)) +
  scale_color_manual(values = c("Blue", "Green", "Orange")) +
  labs(
    x = "Year",
    y = "Number of Grand Slams",
    color = "Player",
    title = "Annual Grand Slam Haul",
    subtitle = "Every year from 2003 - 2022") +
  theme_minimal()
```
```{r, echo = FALSE}
ggplot(Big_3, aes(year, rolling_gs_avg)) +
  geom_line(aes(color = player)) +
  scale_color_manual(values = c("Blue", "Green", "Orange")) +
  labs(
    x = "Year",
    y = "Number of Grand Slams",
    color = "Player",
    title = "3-Year Average Annual Grand Slam Haul",
    subtitle = "Every year from 2003 - 2022") +
  theme_minimal()
```



```{r, echo = FALSE}
ggplot(Big_3, aes(year, rolling_gs_win_rate)) +
  geom_line(aes(color = player)) +
  scale_color_manual(values = c("Blue", "Green", "Orange")) +
  labs(
    x = "Year",
    y = "Grand Slam Win Rate",
    color = "Player",
    title = "3-Year Average Annual Grand Slam Win Rate",
    subtitle = "Every year from 2003 - 2022") +
  theme_minimal()
```



```{r, echo = FALSE}
ggplot(Big_3, aes(year, rolling_mast_win_rate)) +
  geom_line(aes(color = player)) +
  scale_color_manual(values = c("Blue", "Green", "Orange")) +
  labs(
    x = "Year",
    y = "Masters Win Rate",
    color = "Player",
    title = "3-Year Average Annual Masters Win Rate",
    subtitle = "Every year from 2003 - 2022") +
  theme_minimal()
```



```{r, echo = FALSE}
ggplot(Big_3, aes(year, rolling_title_win_rate)) +
  geom_line(aes(color = player)) +
  scale_color_manual(values = c("Blue", "Green", "Orange")) +
  labs(
    x = "Year",
    y = "Title Win Rate",
    color = "Player",
    title = "3-Year Average Annual Title Win Rate",
    subtitle = "Every year from 2003 - 2022") +
  theme_minimal()
```



```{r, echo = FALSE}
ggplot(Big_3, aes(year, h2h_win_rate)) +
  geom_line(aes(color = player)) +
  xlim(2006, 2020) +
  scale_color_manual(values = c("Blue", "Green", "Orange")) +
  labs(
    x = "Year",
    y = "H2H Win Rate",
    color = "Player",
    title = "Annual Big 3 Head to Head Win Rate",
    subtitle = "Every year from 2006 - 2020") +
  theme_minimal()


```


```{r, echo = FALSE}
ggplot(Big_3[Big_3$player == "Djokovic",], aes(year, h2h_total)) +
  geom_line() +
  xlim(2006, 2020) +
  labs(
    x = "Year",
    y = "H2H Matches Played",
    title = "Number of H2H Matches Between Big 3",
    subtitle = "Every year from 2006 - 2020") +
  theme_minimal()
```


```{r, echo = FALSE}
ggplot(Big_3[Big_3$player %in% c("Federer", "Djokovic"),], aes(year, gs_no_nadal)) +
  geom_line(aes(color = player)) +
  scale_color_manual(values = c("Blue", "Green")) +
  labs(
    x = "Year",
    y = "Grand Slams Won",
    color = "Player",
    title = "Federer and Djokovic Annual Grand Slam Haul With No Nadal",
    subtitle = "Every year from 2003 - 2022") +
  theme_minimal()
```



```{r, echo = FALSE}
ggplot(Big_3[Big_3$player %in% c("Nadal", "Djokovic"),], aes(year, gs_no_federer)) +
  geom_line(aes(color = player)) +
  scale_color_manual(values = c("Blue", "Orange")) +
  labs(
    x = "Year",
    y = "Grand Slams Won",
    color = "Player",
    title = "Nadal and Djokovic Annual Grand Slam Haul With No Federer",
    subtitle = "Every year from 2003 - 2022") +
  theme_minimal()
```



```{r, echo = FALSE}
ggplot(Big_3[Big_3$player %in% c("Nadal", "Federer"),], aes(year, gs_no_djokovic)) +
  geom_line(aes(color = player)) +
  scale_color_manual(values = c("Green", "Orange")) +
  labs(
    x = "Year",
    y = "Grand Slams Won",
    color = "Player",
    title = "Federer and Nadal Annual Grand Slam Haul With No Djokovic",
    subtitle = "Every year from 2003 - 2022") +
  theme_minimal()
```